### ISSUE TITLE
Inquiry regarding vulnerability disclosure

### ISSUE THREAD

**Issue by quasar098** [protectai/modelscan#68]
I originally wanted to disclose a vulnerability, but am lost.

The `./pyproject.toml` states modelscan is at version 0.0.0, and the latest release is 0.3.0.

Both of these are not applicable to the security policy, it seems (they are not conforming to `1.X`)

![image](https://github.com/protectai/modelscan/assets/70716985/0e2511df-78ac-4a05-bd9a-92d7f0cb9624)

Are vulnerabilities to be reported currently, or maybe not?

**Comment by chrisking** [comment]
Great catch @quasar098 .  @seanpmorgan can you take a look at this and update the .toml file? 

@quasar098 if you haven't already done so outside of this issue, please checkout https://github.com/protectai/modelscan/blob/main/SECURITY.md and we'll start the triage process on your findings.

**Comment by seanpmorgan** [comment]
Hi @quasar098 thanks for filing this ticket! Couple of things:

1. I [merged a PR](https://github.com/protectai/modelscan/pull/72) that updates our security policy to include 0.x versions. As chris mentioned, please go ahead and submit vulnerabilities as directed in `SECURITY.md`

2. The library version in `pyproject.toml` gets [overwritten when we publish](https://github.com/protectai/modelscan/blob/main/.github/workflows/publish.yml#L34-L36) as a tagged version. This is an easy deployment process for us, but I'm in agreement that it can make it difficult to know the current version by viewing main branch. We're working on a solution to update this in an automated way. 

3. We just [cut release v0.4.0](https://github.com/protectai/modelscan/releases/tag/v0.4.0) today so that is the current version that has been published to pypi.

4. Part of that release included two ([one](https://github.com/protectai/modelscan/pull/69), [two](https://github.com/protectai/modelscan/pull/70)) security patches from picklescan. Is this what you had in mind for your disclosure or is it something else?


Thanks again!

**Comment by quasar098** [comment]
there is that, and more. sending an email regarding it soon
