### ISSUE TITLE
Invalid magic number for pytorch model scan

### ISSUE THREAD

**Issue by bscoj** [protectai/modelscan#82]
**Describe the bug**
Scanning downloaded huggingface models results in invalid magic number error: 

```
--- Errors --- 

Error 1:
The following error was raised during a pytorch scan: 
Invalid magic number for file /opt/modelscan/scan_oss_models/cache/model.pt
```

I tried scanning microsoft/phi-2, Falconsai/medical_summarization, and BAAI/bge-base-en-v1.5 all resulting in the same error. I also tried following along with the tutorial notebook in this repository ([notebooks/pytorch_sentiment_analysis.ipynb](https://github.com/protectai/modelscan/blob/main/notebooks/pytorch_sentiment_analysis.ipynb)) and I get the same invalid magic number error.

**To Reproduce**
```bash
!pip install -q modelscan
!pip install -q torch==2.0.1
!pip install -q transformers==4.36.2
```

```python
import os

import torch
from transformers import AutoModel

model_name = "nlptown/bert-base-multilingual-uncased-sentiment"
cache_dir = "cache"

model = AutoModel.from_pretrained(model_name, cache_dir=cache_dir)
torch.save(model, cache_dir + "/model.pt")
```

```bash
!modelscan --path cache/model.pt
```

Output:
```
No settings file detected at /opt/modelscan/scan_oss_models/modelscan-settings.toml. Using defaults. 

Scanning /opt/modelscan/scan_oss_models/cache/model.pt using modelscan.scanners.PyTorchScan model scan
Scanning /opt/modelscan/scan_oss_models/cache/model.pt:model/data.pkl using modelscan.scanners.PickleScan model scan

--- Summary ---

 No issues found! 🎉

--- Errors --- 

Error 1:
The following error was raised during a pytorch scan: 
Invalid magic number for file /opt/modelscan/scan_oss_models/cache/model.pt
```

**Comment by seanpmorgan** [comment]
Thanks for the report! Looks like a bug was recently introduced. Will prioritize a fix and determine how this was missed in test coverage.

**Comment by seanpmorgan** [comment]
Just to close the loop here. Since PyTorch 1.6 the default serialization format [is a zip-file format](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference). Our previous logic flow (modelscan < 0.4) scanned the zip file as a pickle file and then terminated. Our new modular flow scanned the model as a zipped pickle, but also as a standalone pytorch model since the supported extension matched. That is where we ran into a failing magic number comparison. 

v0.4.3 of modelscan is published and fixes this issue. Test cases have been added for this. Thanks again for reporting!
